"""
Document Identifier & Attribute Generator
==========================================
For each document selected by ``Text_Diverse_Selection.py``, generate
semantic identifiers (information anchors) and query attribute dimensions
to guide downstream diverse query generation.

Usage examples
--------------

# Quick test (5 documents)
python IdAttr_Generator.py \
  --input /data/share/project/zucan/Synthetic_Data_code/SyntheticDataResearch/Main_Pipeline/Results/diverse_texts_20260306_105109_cos060_arguana.jsonl \
  --task arguana --limit 5 \

# Full run
python IdAttr_Generator.py \
  --input Results/diverse_texts_20260303_123205.jsonl \
  --task arguana

# Resume a previous run
python IdAttr_Generator.py \
  --input Results/diverse_texts_20260303_123205.jsonl \
  --task arguana --resume Results/IdAttr_20260303_140000.jsonl

# With custom model
python IdAttr_Generator.py \
  --input Results/diverse_texts_20260303_123205.jsonl \
  --task arguana --model gpt-4o
"""

import argparse
import json
import json5
import logging
import os
import random
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Callable, Dict, List, Optional, Set, Union

from concurrent_runner import run_concurrent

from qwen_agent.agents import Assistant
from qwen_agent.tools.base import BaseTool, register_tool

from HighLevel_Def import HighLevel_Task_Definition
from Few_Shot_Formatter import format_examples, get_examples


# --------------------------------------------------------------------------- #
#  Config                                                                      #
# --------------------------------------------------------------------------- #


@dataclass
class IdAttrConfig:
    """All paths and hyper-parameters for identifier/attribute generation."""

    # Input
    input_path: str = ""
    task_name: str = ""

    # Output
    output_dir: str = "Results"
    log_dir: str = "Logs"

    # LLM
    model: str = "gpt-4o-mini"
    model_server: Optional[str] = None
    api_key: Optional[str] = None

    # Processing (when limit < total docs, randomly sample that many; pipeline test-mode
    # can pass limit/seed from main.py to run Step 3 on a small subset of diverse texts)
    limit: Optional[int] = None
    seed: Optional[int] = None

    # Resume
    resume_path: Optional[str] = None

    # Self-refine: supplementary guidance generated by the prompt calibration loop
    refinement_guidance: Optional[str] = None

    # Concurrency
    concurrency_enabled: bool = False
    max_workers: Optional[int] = None
    jitter: float = 0.0

    # Progress lines on *logger* (e.g. main pipeline log): same semantics as main ``progress_log_interval_sec``.
    progress_log_interval_sec: float = 0.0

    # -- helpers --

    def get_llm_cfg(self) -> dict:
        model_server = self.model_server or os.getenv("OPENAI_BASE_URL")
        api_key = self.api_key or os.getenv("OPENAI_API_KEY")
        return {
            "model": self.model,
            "model_server": model_server if model_server is not None else "",
            "api_key": api_key,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "IdAttrConfig":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

    def to_dict(self) -> dict:
        return {k: getattr(self, k) for k in self.__dataclass_fields__}


# --------------------------------------------------------------------------- #
#  CLI                                                                         #
# --------------------------------------------------------------------------- #


def parse_args(args=None) -> IdAttrConfig:
    p = argparse.ArgumentParser(
        description="Generate identifiers and attributes for diverse documents."
    )
    p.add_argument("--config", type=str, default=None, help="JSON config file.")

    # Input
    p.add_argument(
        "--input", type=str, default=None, dest="input_path",
        help="Input JSONL from Text_Diverse_Selection (fields: doc_id, title, text).",
    )
    p.add_argument(
        "--task", type=str, default=None, dest="task_name",
        help="Task name from HighLevel_Task_Definition (e.g. arguana, msmarco).",
    )

    # Output
    p.add_argument("--output-dir", type=str, default=None)
    p.add_argument("--log-dir", type=str, default=None)

    # LLM
    p.add_argument("--model", type=str, default=None)
    p.add_argument("--model-server", type=str, default=None, dest="model_server")
    p.add_argument("--api-key", type=str, default=None, dest="api_key")

    # Processing
    p.add_argument("--limit", type=int, default=None,
                   help="Max documents to process (default: all).")
    p.add_argument("--seed", type=int, default=None,
                   help="Random seed for sampling when using --limit.")

    # Resume
    p.add_argument("--resume", type=str, default=None, dest="resume_path",
                   help="Existing output JSONL to resume from (skip processed doc_ids).")

    parsed = p.parse_args(args)

    if parsed.config and os.path.isfile(parsed.config):
        with open(parsed.config, "r", encoding="utf-8") as f:
            config = IdAttrConfig.from_dict(json.load(f))
    else:
        config = IdAttrConfig()

    for field in IdAttrConfig.__dataclass_fields__:
        val = getattr(parsed, field, None)
        if val is not None:
            setattr(config, field, val)

    return config


# --------------------------------------------------------------------------- #
#  Logging                                                                     #
# --------------------------------------------------------------------------- #


def _setup_logging(config: IdAttrConfig):
    os.makedirs(config.log_dir, exist_ok=True)
    log_file = os.path.join(
        config.log_dir,
        f"IdAttr_Generator_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log",
    )
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(levelname)s - %(message)s",
        handlers=[logging.FileHandler(log_file), logging.StreamHandler()],
        force=True,
    )
    return logging.getLogger(__name__)


# --------------------------------------------------------------------------- #
#  Prompt                                                                      #
# --------------------------------------------------------------------------- #


def build_idattr_prompt(
    doc: str,
    task_name: str = "",
    refinement_guidance: str = "",
) -> str:
    """Build the LLM prompt for identifier/attribute generation.

    When *task_name* matches a key in ``HighLevel_Task_Definition``, the
    prompt includes task-specific context so the LLM can tailor identifiers
    and attribute dimensions to the downstream IR task.

    Parameters
    ----------
    refinement_guidance : str
        Optional supplementary guidance produced by the self-refine prompt
        calibration loop.  Inserted between Task Context and Core Definitions
        to steer the LLM without altering the structural constraints.
    """
    task_context = ""
    if task_name and task_name in HighLevel_Task_Definition:
        query_type, doc_type, relevance_def = HighLevel_Task_Definition[task_name]
        task_context = f"""
## Task Context (use this to guide your analysis)
- This document is a: {doc_type}
- Queries that will target this document are: {query_type}
- Relevance criteria: {relevance_def}
- Tailor both identifiers and attribute dimensions so they are maximally
  useful for generating diverse queries of the above type.
"""

    refinement_section = ""
    if refinement_guidance and refinement_guidance.strip():
        refinement_section = f"""
## Refined Guidance (from prompt calibration — follow strictly)
{refinement_guidance.strip()}
"""

    return f"""You are a professional data synthesis and NLP expert. Your task is to analyze the document and produce two outputs for downstream diverse and high-quality query generation:
1) Document Identifiers (information anchors)
2) Query Attributes (style/format/constraint dimensions with options)

{task_context}


## Core Definitions (must follow strictly)
- Identifier (Information Anchor): An irreplaceable core entity/relationship extracted directly from the document. It serves as the anchor that diverse queries should target. Do NOT include redundant/irrelevant details. Do NOT use external knowledge.
  - Entity-type: concrete objects in the document (e.g., people, places, events, records/results).
  - Relationship-type: unique relationships/logic between entities stated or implied by the document (e.g., relations between people, places, events, records/results).
- Query Attribute: a non-core feature dimension controlling how queries are asked. Attributes should NOT introduce new core facts; they should steer query diversity while keeping identifiers as the information anchors.
  - Example dimensions (for inspiration only; you may adopt, adapt, or omit): reasoning depth, answer form, topic specificity. These are common dimensions, but not all documents or query types need every one.
  - Brainstorm step: Besides considering the above examples, brainstorm 5-7 more independent dimensions by carefully analyzing THIS document (domain, topic, structure, content type, and what kinds of queries would realistically target it). Each dimension must be independent (no overlap with others), practical for query generation, and have 2-4 mutually exclusive options in mind.
  - Selection step (reason step-by-step): First, analyze the Task Context and the Input Document. Then strictly filter the full pool (example-inspired + brainstormed, typically 8-10 candidate dimensions) **using the Scientific Approach below**, and select exactly 3-6 dimensions that are most useful for diversifying queries over THIS document. Output only these 3-6 selected dimensions in the final JSON.

## 🔬 Critical: Scientific Approach to Attribute Design
Before finalizing your Identifiers and Attributes, you MUST perform a "Task Alignment Analysis". Answer these questions:
1. **WHAT makes this task unique?**
   - Identify specific patterns, challenges, or domain characteristics of {query_type}. (Do not just repeat the task context; explain what it means in practice).
2. **WHY is each selected attribute suitable?**
   - Explain the MATCH between the attribute and the task characteristics. How does it help generate high-quality queries?
3. **MULTIPLE OPTIONS TEST (Crucial):**
   - Does the attribute genuinely have multiple valid, mutually exclusive options for THIS specific task?
   - ⚠️ CRITICAL RULE: If the task context restricts an attribute to only ONE valid option, you MUST NOT select it! (e.g., If it's a reasoning-intensive task, "reasoning depth" should always be "high", so "reasoning depth" is NOT a valid diversifying attribute).
⚠️ This is not a template to fill - this is how experts think.
Blindly applying standard methods without understanding WHY is not acceptable.

## High-Quality Query Attributes Criteria
1. Strictly align with the characteristics of {query_type}.
2. Each selected dimension must have 2-4 mutually exclusive, actionable options applicable to THIS document.

{refinement_section}

## Input Document
doc: {doc}

## Output Format Requirements (MANDATORY, machine-parsable, no deviation)
- Output MUST be a single valid JSON object (RFC 8259).
- Output MUST contain ONLY the JSON object: no Markdown, no code fences, no commentary, no extra keys, no trailing text.
- Use double quotes for all strings and keys. No trailing commas.
- The JSON must start with a single left brace and end with a single right brace.
- Note: In this prompt template you may see doubled braces (e.g., `{{{{` / `}}}}`) due to Python string escaping; your OUTPUT JSON must use normal single braces.

## Hard constraints
- identifiers: 3-10 items; no duplicates/overlap; each must be a standalone anchor.
- attributes: 3-6 dimensions total. Produce them by (1) using the example dimensions only as inspiration, (2) brainstorming from THIS document, then (3) filtering via the Scientific Approach. Each dimension unique; each must have 2-4 options.
- options must be mutually exclusive, actionable, and applicable to THIS document's domain/topic for practical query generation.

## JSON schema (fixed keys; output MUST follow exactly)
{{
  "identifiers": [
    {{
      "type": "entity" | "relationship",
      "identifier": "string (copied/derived from document only; no external info)",
      "label": "string (3-8 words; short unique label)"
    }}
  ],
  "attributes": [
    {{
      "dimension": "string (clear independent dimension name)",
      "options": ["string", "string", "string", "string (optional)"]
    }}
  ]
}}"""


# --------------------------------------------------------------------------- #
#  Self-refine: evaluate & refine prompts                                      #
# --------------------------------------------------------------------------- #


def build_idattr_evaluate_prompt(
    results: List[Dict[str, Any]],
    task_name: str,
) -> str:
    """Build a prompt that asks the LLM to evaluate a batch of IdAttr outputs.

    The evaluator checks whether the generated identifiers and attributes are
    well-aligned with the task's query characteristics and returns structured
    JSON feedback.
    """
    if task_name not in HighLevel_Task_Definition:
        raise ValueError(f"Unknown task_name: {task_name}")

    query_type, doc_type, relevance_def = HighLevel_Task_Definition[task_name]

    samples_json = json.dumps(
        [
            {
                "doc_id": r.get("doc_id", ""),
                "doc": (r.get("doc") or ""),
                "identifiers": r.get("identifiers", []),
                "attributes": r.get("attributes", []),
            }
            for r in results
        ],
        ensure_ascii=False,
        indent=2,
    )

    few_shot_section = format_examples(get_examples(task_name))
## TODO: revise
    return f"""You are a senior quality evaluator for an information retrieval data synthesis pipeline.

## Your Task
Evaluate whether the generated **Identifiers** and **Attributes** across the sample documents below are well-suited for producing diverse, high-quality **{query_type}** queries over **{doc_type}** documents.

## Step-by-step guideline:
1. **Grasp the task.** Understand the context and what good {query_type} queries look like for this task. What characterizes {query_type} queries here?
2. **Learn from examples.** Use the few-shot examples to infer the STYLE, DEPTH, and FOCUS of real {query_type} queries. The identifiers and attributes you evaluate should be able to yield {query_type} queries that match these in character.
3. **Evaluate the samples one by one.** There are multiple sample documents; evaluate **each sample's identifiers and attributes individually** and record issues as you go:
    i. **Compare to the task.** For each sample in turn, check whether its identifiers and attributes align with what good {query_type} queries need: diversity, grounding in the document, and actionable dimensions. Note any mismatch for that specific sample.
    ii. **Apply the criteria.** For each sample, evaluate its identifiers and attributes against the evaluation criteria (Identifier Quality, Attribute-Task Alignment, Multiple Options Test, Coverage, Actionability) and decide whether they are fit for the task. If there are issues, record them clearly for that sample (e.g., "Sample 2 (doc_id X): attribute dimension Y should not have multiple options in this task—it has a fixed characteristic and must be flagged.").
    Keep a clear record of per-sample issues so you can aggregate them in Step 4.
4. **Summarize.** Based on the per-sample issues you noted in Step 3, write a concise summary of the main issues—or confirm quality if none. This summary will go to the prompt engineer for prompt refinement.
5. **Format.** Respond strictly in the required JSON output format.

## Task Context
- Query Type: {query_type}
- Document Type: {doc_type}
- Relevance Definition: {relevance_def}

## Few-Shot Examples (gold-standard query-document pairs for this task)
{few_shot_section}


## Evaluation Criteria (check each rigorously)
1. **Identifier Quality**: Are identifiers diverse, non-redundant, and grounded in the document? Do they cover the key information anchors that {query_type} would realistically target?
2. **Attribute-Task Alignment**: Do the attribute dimensions genuinely help diversify {query_type}? Would each dimension produce meaningfully different queries when its options are varied?
3. **Multiple Options Test**: Does every attribute dimension have 2-4 mutually exclusive options that are ALL valid for this task? If the task context effectively restricts a dimension to a single option, it MUST be flagged.
4. **Coverage**: Across all samples, is there a healthy variety of attribute dimensions, or do the samples all use near-identical dimensions?
5. **Actionability**: Can a query generator actually use these identifiers + attributes to write concrete, natural {query_type} queries?

## Sample IdAttr Outputs (generated by the current prompt)
{samples_json}

## Scoring Rubric (assign exactly one integer score 0–3)
> **Important**: The parenthetical examples (e.g., ...) in each score level are purely illustrative of the *type* of issue at that severity. Do not treat them as a checklist — base your score on the holistic pattern across **all five evaluation criteria above**, not just the dimensions that happen to be mentioned in the examples.

- **Score 3 — Production-Ready**: Identifiers are diverse, specific, and fully grounded in each document's content. All attribute dimensions are genuinely task-aligned with 2–4 mutually exclusive options that are ALL valid for this query type (Multiple Options Test passes for every dimension). Coverage across samples shows healthy variety — samples do not all share near-identical dimension sets. A query generator can immediately produce diverse, natural {query_type} queries without any revision.
- **Score 2 — Acceptable**: Mostly sound, with only minor isolated issues — e.g., 1–2 identifiers that are slightly generic, or one attribute option that is marginally weak. Crucially, **no Multiple Options Test violations** (this is a hard disqualifier for Score 2+), and no systemic dimension repetition across samples. A query generator can still produce useful, diverse queries; only small prompt tweaks are needed.
- **Score 1 — Needs Revision**: Systematic problems undermine query diversity or groundedness. This includes: any Multiple Options Test violation (one or more attribute dimensions effectively restricted to a single valid option), identifiers that are consistently ungrounded or generic across samples (not anchored to document-specific content), or near-identical dimension sets repeating across samples with little variety. A query generator would produce repetitive, low-quality queries.
- **Score 0 — Unusable**: Fundamentally broken. Identifiers are absent, fabricated, or entirely off-topic relative to the documents. Attribute dimensions are structurally invalid, nonsensical, or all collapse to a single valid option. The output cannot be used for query generation at all.

## Output Format (MANDATORY — valid JSON only, no Markdown)
Output a single JSON object:
{{
  "overall_score": 0-3,
  "passed": true if overall_score >= 2 else false,
  "feedback": "Concise summary of the main issues (or confirmation of quality). Be specific: cite which dimensions/identifiers are problematic and WHY. The summary will be sent to the prompt engineer to refine the prompt.",
  "identifier_issues": "Specific issues with identifiers, or 'none'.",
  "attribute_issues": "Specific issues with attribute dimensions/options, or 'none'.",
  "suggestions": "Concrete, actionable suggestions for improving the generation prompt. Focus on what guidance to ADD, not what to remove."
}}

IMPORTANT: Be constructively critical. A "passed" verdict (overall_score >= 2) means the outputs are ready for production use. If you see ANY Multiple Options Test violation or systematic identifier/coverage issue, assign score <= 1 and set passed=false."""


def evaluate_idattr_outputs(
    results: List[Dict[str, Any]],
    task_name: str,
    llm_cfg: dict,
    logger: Optional[logging.Logger] = None,
) -> tuple:
    """Evaluate a batch of IdAttr outputs using the LLM.

    Returns
    -------
    (passed: bool, feedback: str)
    """
    log = logger or logging.getLogger(__name__)
    prompt = build_idattr_evaluate_prompt(results, task_name)

    evaluator = Assistant(llm=llm_cfg)
    raw = ""
    for response in evaluator.run([{"role": "user", "content": prompt}]):
        raw = response[-1]["content"]

    eval_details: dict = {}
    try:
        parsed = json5.loads(raw)
        score = parsed.get("overall_score", 0)
        passed = score >= 2
        parts = []
        if parsed.get("feedback"):
            parts.append(parsed["feedback"])
        if parsed.get("identifier_issues") and parsed["identifier_issues"].lower() != "none":
            parts.append(f"Identifier issues: {parsed['identifier_issues']}")
        if parsed.get("attribute_issues") and parsed["attribute_issues"].lower() != "none":
            parts.append(f"Attribute issues: {parsed['attribute_issues']}")
        if parsed.get("suggestions"):
            parts.append(f"Suggestions: {parsed['suggestions']}")
        feedback = "\n".join(parts)
        eval_details = {
            "score": score,
            "feedback": parsed.get("feedback", ""),
            "identifier_issues": parsed.get("identifier_issues", ""),
            "attribute_issues": parsed.get("attribute_issues", ""),
            "suggestions": parsed.get("suggestions", ""),
        }
        log.info("IdAttr evaluation: passed=%s score=%s", passed, score)
    except Exception as e:
        log.warning("Failed to parse evaluation JSON: %s — treating as not passed", e)
        passed = False
        feedback = f"Evaluation parse error. Raw output:\n{raw[:1000]}"

    return passed, feedback, eval_details


def build_idattr_refine_prompt(
    current_guidance: str,
    results: List[Dict[str, Any]],
    feedback: str,
    task_name: str,
) -> str:
    """Build a prompt that asks the LLM to produce refined guidance.

    The refiner reads the evaluation feedback and the current sample outputs,
    then writes a focused guidance addendum to be inserted into the IdAttr
    generation prompt.
    """
    query_type, doc_type, relevance_def = HighLevel_Task_Definition[task_name]

    samples_brief = json.dumps(
        [
            {
                "doc_id": r.get("doc_id", ""),
                "identifiers": r.get("identifiers", []),
                "attributes": r.get("attributes", []),
            }
            for r in results
        ],
        ensure_ascii=False,
        indent=2,
    )

    prev_guidance_section = f"""
## Previous Guidance (the last addendum that was tried)
There was no previous guidance that was tried before.
"""
    if current_guidance and current_guidance.strip():
        prev_guidance_section = f"""
## Previous Guidance (the last addendum that was tried)
{current_guidance.strip()}
"""

    return f"""You are a prompt engineering expert specializing in information retrieval data synthesis.

## Context
We have a prompt that instructs an LLM to generate **Identifiers** (information anchors) and **Attributes** (query diversity dimensions) for documents. The generated IdAttr will be used downstream to produce diverse **{query_type}** queries over **{doc_type}** documents.

- Relevance Definition: {relevance_def}

## Problem
The current prompt was evaluated on sample documents and received the following feedback. Note: if this feedback contains **specific examples** (e.g., "Identifier X for doc Y is wrong because ..."), you must **abstract** from these examples into **task-level** lessons.

### Evaluation Feedback
{feedback}

### Sample Outputs (from the current prompt)
{samples_brief}

{prev_guidance_section}

## Your Task (two mental steps — output only the final guidance)

**Step 1 — Summarize and abstract (do this mentally, do not output it):**
- Read the feedback and identify **what went wrong** in the examples.
- **Generalize**: For each type of issue, extract the **underlying principle or pattern** that would help the generator avoid that class of error on **any** document, not just the ones in the sample. Ask: "What rule or criterion would prevent this kind of mistake in general?"

**Step 2 — Write Refined Guidance:**
Produce a **Refined Guidance** addendum that encodes those **task-level, query-agnostic** principles. This guidance will be inserted into the generation prompt and must apply to **all** future IdAttr generation, not to specific docs or queries.

## Requirements for the Refined Guidance
1. **Query-agnostic and task-level only**: Do NOT include doc-specific or query-specific fixes (e.g., do not reference particular doc_id, query text, or "for the query about X do Y"). Write only **general rules** that improve IdAttr generation for the whole task.
2. **Derived from feedback**: Every recurring issue type in the feedback should be reflected as a **general principle** in the guidance.
3. **Preserve what works**: If parts of the previous guidance are effective, keep them.
4. **Specific and actionable**: Say exactly WHAT to prefer/avoid and WHY for this task type.
5. **Concise**: 100-300 words. Dense, high-signal, imperative tone (e.g., "Prioritize ...", "Avoid ...", "For {query_type}, ensure ...").
6. **Only guidance about identifiers and attributes generation**: No meta-commentary, no JSON, no Markdown fences.

## Output Format
Output ONLY the refined guidance text (plain text, no JSON wrapping, no Markdown fences). This text will be inserted verbatim into the generation prompt."""


def refine_idattr_guidance(
    current_guidance: str,
    results: List[Dict[str, Any]],
    feedback: str,
    task_name: str,
    llm_cfg: dict,
    logger: Optional[logging.Logger] = None,
    prompt_hook: Optional[Callable[[str], str]] = None,
) -> str:
    """Use the LLM to produce a refined guidance addendum.

    Parameters
    ----------
    prompt_hook : callable, optional
        If provided, called with the fully-built refine prompt string and
        expected to return the (possibly modified) prompt.  Used by
        ``HumanReviewer.review_refine_prompt`` to let a human edit the
        prompt before it is sent to the LLM.

    Returns the new guidance string.
    """
    log = logger or logging.getLogger(__name__)
    prompt = build_idattr_refine_prompt(current_guidance, results, feedback, task_name)
    if prompt_hook is not None:
        prompt = prompt_hook(prompt)

    refiner = Assistant(llm=llm_cfg)
    raw = ""
    for response in refiner.run([{"role": "user", "content": prompt}]):
        raw = response[-1]["content"]

    guidance = raw.strip()
    log.info("Refined guidance generated (length=%d chars)", len(guidance))
    return guidance


# --------------------------------------------------------------------------- #
#  Single-document generation                                                  #
# --------------------------------------------------------------------------- #


def generate_idattr_for_doc(
    doc: Dict[str, Any],
    llm_cfg: dict,
    task_name: str = "",
    refinement_guidance: str = "",
    logger: Optional[logging.Logger] = None,
) -> Dict[str, Any]:
    """Generate identifiers and attributes for a single document.

    Parameters
    ----------
    doc : dict
        Must contain ``doc_id`` and ``doc``.
    llm_cfg : dict
        LLM configuration passed to ``qwen_agent.agents.Assistant``.
    task_name : str
        Key into ``HighLevel_Task_Definition`` for task-aware prompting.
    refinement_guidance : str
        Supplementary guidance from the self-refine calibration loop.
    logger : Logger, optional

    Returns
    -------
    dict
        ``{doc_id, doc, identifiers, attributes}``
    """
    log = logger or logging.getLogger(__name__)

    doc_id = doc.get("doc_id") or ""
    doc_content = doc.get("doc") or ""

    prompt = build_idattr_prompt(
        doc=doc_content, task_name=task_name,
        refinement_guidance=refinement_guidance,
    )

    designer = Assistant(llm=llm_cfg)
    raw_output = ""
    for response in designer.run([{"role": "user", "content": prompt}]):
        raw_output = response[-1]["content"]

    try:
        parsed = json5.loads(raw_output)
    except Exception as e:
        log.warning("Failed to parse LLM JSON for doc_id=%s: %s", doc_id, e)
        parsed = {}

    return {
        "doc_id": doc_id,
        "doc": doc_content,
        "identifiers": parsed.get("identifiers", []),
        "attributes": parsed.get("attributes", []),
    }


# --------------------------------------------------------------------------- #
#  Resume helpers                                                              #
# --------------------------------------------------------------------------- #


def _load_processed_ids(path: str, logger) -> Set[str]:
    """Read an existing output JSONL and return the set of already-processed doc_ids."""
    processed: Set[str] = set()
    if not path or not os.path.isfile(path):
        return processed
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                did = obj.get("doc_id")
                if did:
                    processed.add(did)
            except Exception:
                pass
    logger.info("Resume: loaded %d already-processed doc_ids from %s", len(processed), path)
    return processed


def _normalize_surrogates(value: Any) -> Any:
    """Recursively replace UTF-16 surrogate code points with valid Unicode."""
    if isinstance(value, str):
        if not any(0xD800 <= ord(char) <= 0xDFFF for char in value):
            return value
        return value.encode("utf-16", "surrogatepass").decode("utf-16", "replace")
    if isinstance(value, list):
        return [_normalize_surrogates(item) for item in value]
    if isinstance(value, dict):
        return {
            _normalize_surrogates(key): _normalize_surrogates(item)
            for key, item in value.items()
        }
    return value


# --------------------------------------------------------------------------- #
#  Core pipeline                                                               #
# --------------------------------------------------------------------------- #


def generate_idattr(
    config: Optional[Union[IdAttrConfig, dict]] = None,
    logger: Optional[logging.Logger] = None,
) -> str:
    """Generate identifiers and attributes for all documents in the input file.

    Returns the path to the output JSONL file.

    When ``logger`` is provided (e.g. when called from main pipeline), that logger
    is used and the root logging config is left unchanged. When ``logger`` is None
    (e.g. when run as standalone script), logging is configured here and output
    goes to IdAttr_Generator_*.log.
    """
    if config is None:
        config = IdAttrConfig()
    elif isinstance(config, dict):
        config = IdAttrConfig.from_dict(config)

    if logger is None:
        logger = _setup_logging(config)

    try:
        os.makedirs(config.output_dir, exist_ok=True)

        # ---- Validate inputs -------------------------------------------------
        if not config.input_path or not os.path.isfile(config.input_path):
            raise FileNotFoundError(f"Input file not found: {config.input_path}")

        if config.task_name and config.task_name not in HighLevel_Task_Definition:
            logger.warning(
                "task_name '%s' not in HighLevel_Task_Definition; "
                "proceeding without task context.", config.task_name,
            )

        llm_cfg = config.get_llm_cfg()
        logger.info("LLM config: model=%s", llm_cfg["model"])

        # ---- Load input documents --------------------------------------------
        logger.info("Loading documents from %s ...", config.input_path)
        docs: List[Dict[str, Any]] = []
        with open(config.input_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    obj = json.loads(line)
                    docs.append(obj)
                except Exception as e:
                    logger.warning("Skipping malformed line: %s", e)

        total = len(docs)
        logger.info("Loaded %d documents.", total)

        # ---- Sampling --------------------------------------------------------
        if config.limit is not None and config.limit < total:
            if config.seed is not None:
                random.seed(config.seed)
            docs = random.sample(docs, config.limit)
            logger.info("Sampled %d documents (seed=%s).", len(docs), config.seed)

        # ---- Resume ----------------------------------------------------------
        processed_ids: Set[str] = set()
        output_file: str
        open_mode: str

        if config.resume_path and os.path.isfile(config.resume_path):
            processed_ids = _load_processed_ids(config.resume_path, logger)
            output_file = config.resume_path
            open_mode = "a"
        else:
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_file = os.path.join(config.output_dir, f"IdAttr_{ts}.jsonl")
            open_mode = "w"

        docs_to_process = [d for d in docs if d.get("doc_id") not in processed_ids]
        num_skipped = len(docs) - len(docs_to_process)
        if num_skipped > 0:
            logger.info("Skipping %d already-processed documents.", num_skipped)
        num_to_process = len(docs_to_process)
        logger.info("Documents to process: %d", num_to_process)

        if num_to_process == 0:
            logger.info("Nothing to process. Output: %s", output_file)
            return output_file

        # ---- Process documents -----------------------------------------------
        logger.info(
            "Processing %d documents (concurrency=%s, max_workers=%s, jitter=%.2f) ...",
            num_to_process, config.concurrency_enabled, config.max_workers, config.jitter,
        )

        def _process_one(doc: Dict[str, Any]) -> Optional[Dict[str, Any]]:
            doc_id = doc.get("doc_id", "unknown")
            try:
                return generate_idattr_for_doc(
                    doc=doc,
                    llm_cfg=llm_cfg,
                    task_name=config.task_name,
                    refinement_guidance=config.refinement_guidance or "",
                    logger=logger,
                )
            except Exception as e:
                logger.error("Error processing doc_id=%s: %s", doc_id, e)
                return None

        results = run_concurrent(
            _process_one,
            [{"doc": doc} for doc in docs_to_process],
            enabled=config.concurrency_enabled,
            max_workers=config.max_workers,
            jitter=config.jitter,
            progress_logger=logger,
            progress_label="Step 3.1 IdAttr generation",
            progress_interval_sec=config.progress_log_interval_sec,
        )

        success_count = 0
        with open(output_file, open_mode, encoding="utf-8") as out_f:
            for result in results:
                if result is not None:
                    normalized_result = _normalize_surrogates(result)
                    out_f.write(json.dumps(normalized_result, ensure_ascii=False) + "\n")
                    success_count += 1

        logger.info(
            "Done. %d/%d documents processed successfully.", success_count, num_to_process,
        )
        logger.info("Output: %s", output_file)
        return output_file

    except Exception:
        logger.error("Error in generate_idattr", exc_info=True)
        raise


# --------------------------------------------------------------------------- #
#  Tool                                                                        #
# --------------------------------------------------------------------------- #


@register_tool("idattr_generator")
class IdAttrGenerator(BaseTool):
    """File-in / file-out wrapper around ``generate_idattr()``.

    Reads a JSONL of documents produced by ``Text_Diverse_Selection``,
    generates identifiers and attributes for each document, and writes
    results to a new JSONL under ``output_dir``.  Returns the output
    file path so downstream pipeline steps can chain directly.
    """

    description = (
        "Generate semantic identifiers and query attribute dimensions for "
        "every document in an input JSONL file. Writes results to a new "
        "JSONL and returns its path."
    )
    parameters = [
        # ---- Input -----------------------------------------------------------
        {
            "name": "input_path",
            "type": "string",
            "description": (
                "Path to the input JSONL file (output of Text_Diverse_Selection). "
                "Each line must have fields: doc_id, text, and optionally title."
            ),
            "required": True,
        },
        {
            "name": "task_name",
            "type": "string",
            "description": (
                'Task key from HighLevel_Task_Definition (e.g. "msmarco"). '
                "Enables task-aware prompting. Case-insensitive."
            ),
            "required": False,
        },
        # ---- Output ----------------------------------------------------------
        {
            "name": "output_dir",
            "type": "string",
            "description": 'Directory for the output JSONL. Defaults to "Results".',
            "required": False,
        },
        {
            "name": "log_dir",
            "type": "string",
            "description": 'Directory for log files. Defaults to "Logs".',
            "required": False,
        },
        # ---- Processing ------------------------------------------------------
        {
            "name": "limit",
            "type": "number",
            "description": "Max number of documents to process. Omit to process all.",
            "required": False,
        },
        {
            "name": "seed",
            "type": "number",
            "description": "Random seed used when sampling with --limit.",
            "required": False,
        },
        # ---- Resume ----------------------------------------------------------
        {
            "name": "resume_path",
            "type": "string",
            "description": (
                "Path to an existing output JSONL to resume from. "
                "Already-processed doc_ids are skipped; new results are appended."
            ),
            "required": False,
        },
    ]

    def call(self, params: str, **kwargs) -> str:
        params_dict = json5.loads(params)

        _kwarg_cfg: dict = kwargs.get("llm_cfg", {})

        config = IdAttrConfig(
            input_path=params_dict.get("input_path", ""),
            task_name=(params_dict.get("task_name") or "").lower(),
            output_dir=params_dict.get("output_dir") or "Results",
            log_dir=params_dict.get("log_dir") or "Logs",
            model=(
                _kwarg_cfg.get("model")
                or "gpt-4o-mini"
            ),
            model_server=(
                _kwarg_cfg.get("model_server")
                or os.getenv("OPENAI_BASE_URL")
            ),
            api_key=(
                _kwarg_cfg.get("api_key")
                or os.getenv("OPENAI_API_KEY")
            ),
            limit=params_dict.get("limit"),
            seed=params_dict.get("seed"),
            resume_path=params_dict.get("resume_path"),
        )

        output_file = generate_idattr(config)
        return json5.dumps({"output_path": output_file}, ensure_ascii=False)


# --------------------------------------------------------------------------- #
#  Entry                                                                       #
# --------------------------------------------------------------------------- #

if __name__ == "__main__":
    cfg = parse_args()
    generate_idattr(cfg)
